# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: gvsu-snack-limit-svc

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  role: arn:aws:iam::236711959566:role/lambda_callsheet
  runtime: nodejs4.3

# you can overwrite defaults here
  stage: demo
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: snacklimits/hello
          method: get
  get:
    handler: handler.get
    timeout: 3
    events:
      - http:
          path: snacklimits/{slid}
          method: get
          cors: true
#          authorizer:
#            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_HqCU8elu4
  list:
    handler: handler.get
    timeout: 3
    events:
      - http:
          path: snacklimits
          method: get
          cors: true
#          authorizer:
#            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_HqCU8elu4
  create:
    handler: handler.create
    timeout: 3
    events:
      - http:
          path: snacklimits
          method: post
          cors: true
#          authorizer:
#            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_HqCU8elu4
  update:
    handler: handler.update
    timeout: 3
    events:
      - http:
          path: snacklimits
          method: put
          cors: true
#          authorizer:
#            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_HqCU8elu4
  delete:
    handler: handler.delete
    timeout: 3
    events:
      - http:
          path: snacklimits/{slid}
          method: delete
          cors: true
